version: "3.9"

services:
  base-service:
    # A gunicorn WSGI HTTP Server that
    # runs the Mathesar App.
    container_name: mathesar_service
    image: mathesar/mathesar-prod:latest
    environment:
      - MODE=${MODE-PRODUCTION}
      - DEBUG=${DEBUG-False}
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE-config.settings.production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS-*}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_DATABASE_KEY=${DJANGO_DATABASE_KEY-default}
      - DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL-postgres://mathesar:mathesar@mathesar_db:5432/mathesar_django}
      - MATHESAR_DATABASES=${MATHESAR_DATABASES-(mathesar_tables|postgresql://mathesar:mathesar@mathesar_db:5432/mathesar)}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
    command: ./run.sh
    volumes:
      - static:/code/static
      - media:/code/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
volumes:
  media:
  static:
